"""Constantes visuales - Paleta de colores y tipografías"""

# Fondos y superficies
COLOR_FONDO          = '#0D0F1A'  
COLOR_SUPERFICIE     = '#14162A' 
COLOR_TEXTO          = '#D8DCF0'  
COLOR_TEXTO_BTN      = '#FFFFFF'   

COLOR_FILA_PAR       = '#181A30'  
COLOR_SELECCIONADO   = '#1C3A78'  


# ── Sistema de botones (3 categorías)
COLOR_BTN_PRIMARIO       = '#2F52CC'
COLOR_BTN_PRIMARIO_ACT   = '#2040AA'

COLOR_BTN_SECUNDARIO     = '#363A52'
COLOR_BTN_SECUNDARIO_ACT = '#272A3E'

COLOR_BTN_PELIGRO        = '#8B2132'
COLOR_BTN_PELIGRO_ACT    = '#6A1826'

# Alias semánticos
COLOR_BTN_NUEVO          = COLOR_BTN_PRIMARIO
COLOR_BTN_NUEVO_ACT      = COLOR_BTN_PRIMARIO_ACT

COLOR_BTN_GUARDAR        = COLOR_BTN_PRIMARIO
COLOR_BTN_GUARDAR_ACT    = COLOR_BTN_PRIMARIO_ACT

COLOR_BTN_EDITAR         = COLOR_BTN_PRIMARIO
COLOR_BTN_EDITAR_ACT     = COLOR_BTN_PRIMARIO_ACT

COLOR_BTN_BUSCAR         = COLOR_BTN_PRIMARIO
COLOR_BTN_BUSCAR_ACT     = COLOR_BTN_PRIMARIO_ACT

COLOR_BTN_HISTORIAL      = COLOR_BTN_PRIMARIO
COLOR_BTN_HISTORIAL_ACT  = COLOR_BTN_PRIMARIO_ACT

COLOR_BTN_CANCELAR       = COLOR_BTN_SECUNDARIO
COLOR_BTN_CANCELAR_ACT   = COLOR_BTN_SECUNDARIO_ACT

COLOR_BTN_LIMPIAR        = COLOR_BTN_SECUNDARIO
COLOR_BTN_LIMPIAR_ACT    = COLOR_BTN_SECUNDARIO_ACT

COLOR_BTN_CALENDARIO     = COLOR_BTN_SECUNDARIO
COLOR_BTN_CALENDARIO_ACT = COLOR_BTN_SECUNDARIO_ACT

# Tipografía
FUENTE_ETIQUETA = ('Segoe UI', 13, 'bold')
FUENTE_ENTRADA  = ('Segoe UI', 13)
FUENTE_BTN      = ('Segoe UI', 11, 'bold')
